# Generated by Django 4.1 on 2022-08-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_registerasrider_rentingservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookaride',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registerasrider',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentingservice',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
