# Generated by Django 4.1 on 2022-08-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_alter_bookaride_phone_alter_emergency_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentingservice',
            name='Occupation',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
