# Generated by Django 4.1 on 2022-08-12 14:28

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0004_alter_rentingservice_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('aadhar', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('phoneno', models.IntegerField(blank=True, null=True)),
                ('caddress', ckeditor.fields.RichTextField()),
                ('paddress', ckeditor.fields.RichTextField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('dlno', models.CharField(max_length=30)),
                ('rcno', models.CharField(max_length=30)),
                ('is_bike_active', models.BooleanField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='RegisterAsRider',
        ),
    ]
