# Generated by Django 4.1 on 2022-08-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0006_remove_emergency_dob_alter_emergency_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookaride',
            name='DOB',
        ),
    ]
