# Generated by Django 4.1 on 2022-08-12 11:05

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterAsRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('aadhar_no', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.IntegerField()),
                ('curr_address', ckeditor.fields.RichTextField()),
                ('perm_address', ckeditor.fields.RichTextField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('dl_no', models.CharField(max_length=30)),
                ('is_bike_active', models.BooleanField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='RentingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('city', models.CharField(choices=[('Gadag', 'Gadag'), ('Hubli-Dharwad', 'Hubli-Dharwad'), ('Belagavi', 'Belagavi'), ('Haveri', 'Haveri'), ('Mysore', 'Mysore'), ('Bengalore', 'Bengalore'), ('Mandya', 'Mandya'), ('Hassan', 'Hassan')], max_length=20)),
                ('Occupation', models.CharField(max_length=40)),
                ('curr_address', ckeditor.fields.RichTextField()),
                ('perm_address', ckeditor.fields.RichTextField()),
                ('driving_lic_no', models.CharField(max_length=30)),
                ('rent_hrs', models.IntegerField(blank=True, null=True)),
                ('rent_chars', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameField(
            model_name='bookaride',
            old_name='address',
            new_name='drop_addr',
        ),
        migrations.RenameField(
            model_name='bookaride',
            old_name='message',
            new_name='pick_up',
        ),
        migrations.RenameField(
            model_name='emergency',
            old_name='address',
            new_name='drop_addr',
        ),
        migrations.RenameField(
            model_name='emergency',
            old_name='message',
            new_name='pick_up',
        ),
        migrations.AddField(
            model_name='bookaride',
            name='city',
            field=models.CharField(choices=[('Gadag', 'Gadag'), ('Hubli-Dharwad', 'Hubli-Dharwad'), ('Belagavi', 'Belagavi'), ('Haveri', 'Haveri'), ('Mysore', 'Mysore'), ('Bengalore', 'Bengalore'), ('Mandya', 'Mandya'), ('Hassan', 'Hassan')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookaride',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='emergency',
            name='city',
            field=models.CharField(choices=[('Gadag', 'Gadag'), ('Hubli-Dharwad', 'Hubli-Dharwad'), ('Belagavi', 'Belagavi'), ('Haveri', 'Haveri'), ('Mysore', 'Mysore'), ('Bengalore', 'Bengalore'), ('Mandya', 'Mandya'), ('Hassan', 'Hassan')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergency',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='emergency',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookaride',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
