# Generated by Django 4.1 on 2022-08-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_registerasrider_rentingservice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerasrider',
            old_name='ardhar_no',
            new_name='aadhar_no',
        ),
    ]
