# Generated by Django 4.1 on 2022-08-12 14:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phoneno', models.IntegerField()),
                ('caddress', ckeditor.fields.RichTextField()),
                ('paddress', ckeditor.fields.RichTextField()),
                ('dlno', models.IntegerField()),
                ('rcno', models.IntegerField()),
                ('aadhar', models.IntegerField()),
            ],
        ),
    ]
