# Generated by Django 4.1 on 2022-08-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_careers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='city',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='careers',
            name='dlno',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='careers',
            name='rcno',
            field=models.CharField(max_length=30),
        ),
    ]
