# Generated by Django 4.1 on 2022-08-13 02:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_rename_city_services_title_alter_careers_dlno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='caddress',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='dlno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='fname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='lname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='paddress',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='phoneno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='rcno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
