# Generated by Django 4.1 on 2022-08-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_alter_careers_caddress_alter_careers_dlno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='aadhar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
