# Generated by Django 4.1 on 2022-08-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='city',
            new_name='title',
        ),
    ]
