# Generated by Django 4.1 on 2022-08-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_alter_contact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='services',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='services',
            name='subhead',
        ),
        migrations.RemoveField(
            model_name='services',
            name='title',
        ),
    ]
