# Generated by Django 4.1 on 2022-08-15 14:21

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookARide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('city', models.CharField(choices=[('Gadag', 'Gadag'), ('Hubli-Dharwad', 'Hubli-Dharwad'), ('Belagavi', 'Belagavi'), ('Haveri', 'Haveri'), ('Mysore', 'Mysore'), ('Bengalore', 'Bengalore'), ('Mandya', 'Mandya'), ('Hassan', 'Hassan')], max_length=20)),
                ('pick_up', ckeditor.fields.RichTextField()),
                ('drop_addr', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=20, null=True)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('phoneno', models.IntegerField()),
                ('caddress', ckeditor.fields.RichTextField()),
                ('paddress', ckeditor.fields.RichTextField()),
                ('dlno', models.CharField(max_length=30)),
                ('rcno', models.CharField(max_length=30)),
                ('aadhar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('city', models.CharField(choices=[('Gadag', 'Gadag'), ('Hubli-Dharwad', 'Hubli-Dharwad'), ('Belagavi', 'Belagavi'), ('Haveri', 'Haveri'), ('Mysore', 'Mysore'), ('Bengalore', 'Bengalore'), ('Mandya', 'Mandya'), ('Hassan', 'Hassan')], max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pick_up', ckeditor.fields.RichTextField()),
                ('drop_addr', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='RentingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
                ('city', models.CharField(choices=[('Gadag', 'Gadag'), ('Hubli-Dharwad', 'Hubli-Dharwad'), ('Belagavi', 'Belagavi'), ('Haveri', 'Haveri'), ('Mysore', 'Mysore'), ('Bengalore', 'Bengalore'), ('Mandya', 'Mandya'), ('Hassan', 'Hassan')], max_length=20)),
                ('Occupation', models.CharField(blank=True, max_length=40, null=True)),
                ('curr_address', ckeditor.fields.RichTextField()),
                ('perm_address', ckeditor.fields.RichTextField()),
                ('driving_lic_no', models.CharField(max_length=30)),
                ('rent_hrs', models.IntegerField(blank=True, null=True)),
                ('rent_chars', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
