# Generated by Django 4.1 on 2022-08-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careers',
            old_name='fname',
            new_name='firstname',
        ),
    ]
