# Generated by Django 4.1 on 2022-08-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_rename_fname_careers_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='firstname',
            field=models.CharField(max_length=20, null=True, verbose_name='firstname'),
        ),
    ]
