# Generated by Django 4.1 on 2022-08-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_alter_careers_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careers',
            old_name='phoneno',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='careers',
            name='caddress',
        ),
        migrations.RemoveField(
            model_name='careers',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='careers',
            name='paddress',
        ),
        migrations.RemoveField(
            model_name='careers',
            name='rcno',
        ),
        migrations.AddField(
            model_name='careers',
            name='curr_address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='careers',
            name='fname',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='careers',
            name='perm_address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='careers',
            name='dlno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='careers',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
